name: 'Get files'
description: 'Saves lists of changed files'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  files-all:
    description: Array of all changed files (JSON string)
  files-added:
    description: Array of added files (JSON string)
  files-deleted:
    description: Array of deleted files (JSON string)
  files-modified:
    description: Array of modified files (JSON string)
branding:
  icon:  'search'
  color: 'gray-dark'
