name: 'Get files'
description: 'Saves lists of changed files'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  configuration-path:
    description: 'The path for configurations'
    required: true
    default: '.github/labeler.yml'
  file-size-limit:
    description: 'Maximum file size in bytes'
    required: true
    default: '1000000' # Default 1MB
outputs:
  time: # id of output
    description: 'The time the step ran'
  files-all:
    description: Array of all changed files (JSON string)
  files-added:
    description: Array of added files (JSON string)
  files-deleted:
    description: Array of deleted files (JSON string)
  files-modified:
    description: Array of modified files (JSON string)
branding:
  icon:  'search'
  color: 'gray-dark'
